## HTML passing with Beautiful Soup: A Mini Project
#### scrape data from a public website
#### organize the data as a dataframe
#### export the data as an excel sheet

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://www.bbc.com/sport/football/premier-league/top-scorers"

In [4]:
player_names = []
player_teams = []
goals = []
assists = []
num_matches = []
shots= []
try:
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, 'html.parser')
    players = soup.find('tbody').find_all('tr', class_='ssrcss-dhlz6k-TableRowBody e1icz100')
    
    for player in players:
        player_name = player.find('div', class_ = "ssrcss-m6ah29-PlayerName e1n8xy5b1").get_text(strip = True)
        player_team = player.find('div', class_ = "ssrcss-qvpga1-TeamsSummary e1n8xy5b0").get_text(strip = True)
        goals_scored = int(player.find('div','ssrcss-8k20kk-CellWrapper ef9ipf0').get_text(strip= True))
        
        stats =  player.find_all('div',class_ = 'ssrcss-150z8d-CellWrapper ef9ipf0')
        assists_made = int(stats[0].get_text(strip=True))
        matches_played = int(stats[2].get_text(strip=True))
        shots_taken = int(stats[-3].get_text(strip=True))
        
        player_names.append(player_name)
        player_teams.append(player_team)
        goals.append(goals_scored)
        assists.append(assists_made)
        num_matches.append(matches_played)
        shots.append(shots_taken)

    data = {
        'player': player_names,
        'team' : player_teams,
        'matches' : num_matches,
        'goals' : goals,
        'assists': assists,
        'shots' : shots
    }
    df_players = pd.DataFrame(data)

In [5]:
df_players

              player            team  matches  goals  assists  shots
0      Mohamed Salah       Liverpool       30     27       17    107
1         E. Haaland        Man City       28     21        3    102
2            A. Isak       Newcastle       26     20        5     72
3            C. Wood    Nottm Forest       29     18        3     53
4          B. Mbeumo       Brentford       30     16        5     65
5          C. Palmer         Chelsea       29     14        7    104
6           Y. Wissa       Brentford       27     14        2     66
7         O. Watkins     Aston Villa       30     13        6     72
8      Matheus Cunha          Wolves       26     13        4     86
9        J. Kluivert     Bournemouth       28     12        6     56
10         J. Mateta  Crystal Palace       28     12        2     56
11          L. Delap         Ipswich       29     11        2     59
12        R. Jiménez          Fulham       30     10        3     79
13  J. Strand Larsen          Wolves       28     10        2     41
14       J. Maddison       Tottenham       28      9        5     38
15        N. Jackson         Chelsea       24      9        5     65
16           L. Díaz       Liverpool       29      9        5     57
17        K. Havertz         Arsenal       21      9        3     52
18        B. Johnson       Tottenham       27      9        2     49
19   Bruno Fernandes         Man Utd       29      8        9     78
20        João Pedro        Brighton       24      8        6     43
21          C. Gakpo       Liverpool       27      8        3     44
22     Son Heung-Min       Tottenham       27      7        9     54
23         M. Rogers     Aston Villa       29      7        6     45
24          J. Bowen        West Ham       26      7        5     67
25        D. Welbeck        Brighton       23      7        4     42
26       D. Ouattara     Bournemouth       27      7        4     54
27     D. Kulusevski       Tottenham       27      7        4     43
28          A. Iwobi          Fulham       30      7        4     53
29        A. Semenyo     Bournemouth       29      7        4    107
30        N. Madueke         Chelsea       24      7        3     64
31        D. Solanke       Tottenham       21      7        3     52
32           I. Sarr  Crystal Palace       29      7        3     43
33          J. Vardy       Leicester       28      7        3     47
34         K. Mitoma        Brighton       30      7        3     49
35          P. Foden        Man City       24      7        2     50
36         K. Schade       Brentford       30      7        2     42
37     Rodrigo Muniz          Fulham       29      7        1     34
38         T. Souček        West Ham       28      7        1     46
39          J. Durán     Aston Villa       20      7        0     31
40         Evanilson     Bournemouth       23      7        0     53

In [6]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   player   41 non-null     object
 1   team     41 non-null     object
 2   matches  41 non-null     int64
 3   goals    41 non-null     int64
 4   assists  41 non-null     int64
 5   shots    41 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.1+ KB

In [9]:
df_players.columns

Index(['player', 'team', 'matches', 'goals', 'assists', 'shots'], dtype='object')

In [30]:
df_players.isnull().sum()

player     0
team       0
matches    0
goals      0
assists    0
shots      0
dtype: int64

In [7]:
!pip install openpyxl
!pip install xlsxwriter

Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: xlsxwriter in c:\users\admin\anaconda3\lib\site-packages (3.2.2)

In [8]:
df_players.to_excel('EPL Top Scorers.xlsx', index= False, engine='xlsxwriter')